### PR TITLE
"Login on discordlist.gg" instead of "top.gg"

### PR DESCRIPTION
**Pull request by thomasbnt**
## Description
In the documentation part https://docs.discordanalytics.xyz/get-started/votes-integration#configuration, we have now (thanks) discordlist.gg, but the first link is top.gg.
image

### CODE REVIEW

**Comment by thomasbnt** [comment]
Ah I think it's under development. Sorry for the inconvenience. 
image

**Comment by Nonolanlan1007** [comment]
> Ah I think it's under development. Sorry for the inconvenience. 
> 
> image
> 
> 

What link does you provide?

**Review by Nonolanlan1007 — APPROVED** [review]

**Comment by thomasbnt** [comment]
Hello @Nonolanlan1007, the URL come from the documentation
> https://discordanalytics.xyz/api/bots/666310082836955136/votes/webhooks/discordlist

image

**Comment by Nonolanlan1007** [comment]
It was a mistake in the API 😅
It's currently in deployment, and will be fixed in a moment :) 

EDIT: It's deployed ^^

**Pull request merged**
